language: android
sudo: false
jdk: oraclejdk8
os:
  - linux


before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager tools


android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-27


script: ./gradlew --daemon test

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


    buildToolsVersion = '27.0.3'
